const DATA = [
  {
    author: 'John_Doe',
    video: "PxqB_lQNdto",
    language: 'English',
    rating: 4.5,
    download: "https://www.google.com",
  },
  {
    author: 'Gabe_Newell',
    video: "PxqB_lQNdto",
    language: 'English',
    rating: 4.8,
    download: "https://www.bing.com",
  },
  {
    author: 'Miguel_de_Cervantes',
    video: "PxqB_lQNdto",
    language: 'Spanish',
    rating: 4,
    download: "https://www.yahoo.com",
  },
  // Replicate the existing data to reach a total of 25 items
  {
    author: 'Author_4',
    video: "PxqB_lQNdto",
    language: 'Language 4',
    rating: 3.7,
    download: "https://www.example1.com",
  },
  {
    author: 'Author_5',
    video: "PxqB_lQNdto",
    language: 'Language 5',
    rating: 4.2,
    download: "https://www.example2.com",
  },
  {
    author: 'Author_6',
    video: "PxqB_lQNdto",
    language: 'Language 6',
    rating: 4.8,
    download: "https://www.example3.com",
  },
  {
    author: 'Author_7',
    video: "PxqB_lQNdto",
    language: 'Language 7',
    rating: 3.5,
    download: "https://www.example4.com",
  },
  {
    author: 'Author_8',
    video: "PxqB_lQNdto",
    language: 'Language 8',
    rating: 4.1,
    download: "https://www.example5.com",
  },
  {
    author: 'Author_9',
    video: "PxqB_lQNdto",
    language: 'Language 9',
    rating: 4.9,
    download: "https://www.example6.com",
  },
  {
    author: 'Author_10',
    video: "PxqB_lQNdto",
    language: 'Language 10',
    rating: 3.0,
    download: "https://www.example7.com",
  },
  {
    author: 'Author_11',
    video: "PxqB_lQNdto",
    language: 'Language 11',
    rating: 4.7,
    download: "https://www.example8.com",
  },
  {
    author: 'Author_12',
    video: "PxqB_lQNdto",
    language: 'Language 12',
    rating: 3.2,
    download: "https://www.example9.com",
  },
  {
    author: 'Author_13',
    video: "PxqB_lQNdto",
    language: 'Language 13',
    rating: 4.6,
    download: "https://www.example10.com",
  },
  {
    author: 'Author_14',
    video: "PxqB_lQNdto",
    language: 'Language 14',
    rating: 4.0,
    download: "https://www.example11.com",
  },
  {
    author: 'Author_15',
    video: "PxqB_lQNdto",
    language: 'Language 15',
    rating: 3.9,
    download: "https://www.example12.com",
  },
  {
    author: 'Author_16',
    video: "PxqB_lQNdto",
    language: 'Language 16',
    rating: 4.3,
    download: "https://www.example13.com",
  },
  {
    author: 'Author_17',
    video: "PxqB_lQNdto",
    language: 'Language 17',
    rating: 3.6,
    download: "https://www.example14.com",
  },
  {
    author: 'Author_18',
    video: "PxqB_lQNdto",
    language: 'Language 18',
    rating: 4.4,
    download: "https://www.example15.com",
  },
  {
    author: 'Author_19',
    video: "PxqB_lQNdto",
    language: 'Language 19',
    rating: 3.8,
    download: "https://www.example16.com",
  },
  {
    author: 'Author_20',
    video: "PxqB_lQNdto",
    language: 'Language 20',
    rating: 4.5,
    download: "https://www.example17.com",
  },
  {
    author: 'Author_21',
    video: "PxqB_lQNdto",
    language: 'Language 21',
    rating: 3.4,
    download: "https://www.example18.com",
  },
  {
    author: 'Author_22',
    video: "PxqB_lQNdto",
    language: 'Language 22',
    rating: 4.2,
    download: "https://www.example19.com",
  },
  {
    author: 'Author_23',
    video: "PxqB_lQNdto",
    language: 'Language 23',
    rating: 3.3,
    download: "https://www.example20.com",
  },
  {
    author: 'Author_24',
    video: "PxqB_lQNdto",
    language: 'Language 24',
    rating: 4.1,
    download: "https://www.example21.com",
  },
  {
    author: 'Author_25',
    video: "PxqB_lQNdto",
    language: 'Language 25',
    rating: 3.1,
    download: "https://www.example22.com",
  }
];



export default DATA